project/urls.py
from django.urls import path, include

urlpatterns = [
    path('users/', include('users.urls', namespace='users')),
    path('rooms/', include('rooms.urls', namespace='rooms')),
    path('server_notices/', include('server_notices.urls', namespace='server_notices')),
    path('', include('dashboard.urls', namespace='dashboard'))
]

rooms/urls.py
from django.urls import path

from .views import RoomsView, RoomView

app_name = 'rooms'

urlpatterns = [
    path('<str:room_id>/', RoomView.as_view(), name='detail'),
    path('', RoomsView.as_view(), name='list')
]

rooms/models.py
from django.db import models

# Create your models here.

rooms/views.py
from django.conf import settings
from django.core.cache import cache
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import Http404
from django.views.generic import ListView, TemplateView

from .helpers import load_rooms
from django.conf import settings


class RoomsView(ListView):
    template_name = 'rooms/rooms.html'
    paginate_by = 30

    def get_queryset(self) -> tuple:
        return tuple(cache.get(settings.CACHED_ROOMS, {}).values())

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        paginator = Paginator(self.object_list, self.paginate_by)
        page: str = self.request.GET.get('page')

        try:
            rooms = paginator.get_page(page)
        except PageNotAnInteger:
            rooms = paginator.get_page(1)
        except EmptyPage:
            rooms = paginator.get_page(paginator.num_pages)

        context['rooms'] = rooms
        context['cached_rooms_updated_at'] = cache.get(settings.CACHED_USERS_UPDATED_AT, None)
        context['total_rooms'] = paginator.count

        context['rooms_page_active'] = True

        return context


class RoomView(TemplateView):
    template_name = 'rooms/room.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()

        room_id = self.kwargs['room_id']
        room = cache.get(settings.CACHED_ROOMS, {}).get(room_id, None)
        if room is None:
            raise Http404('User not found.')

        context['room'] = room

        return context

templates/rooms/room.html
{% extends '_base.html' %}

{% block content %}
    <div class="my-2 p-2 d-flex flex-wrap justify-content-center">
        <div class="flex-shrink-0 m-2 d-flex flex-column">
            <img style="object-fit: cover"
                 src="{{ room.avatar_url|default:'https://cdn3.emoji.gg/emojis/9889-pain.gif' }}" alt="{{ room.name }}"
                 class="rounded text-light bg-light"
                 width="200px" height="200px">
        </div>
        <div class="flex-grow-1 m-2">
            <ul class="list-group">
                <li class="list-group-item text-center">INFO</li>
                <li class="list-group-item">ID: {{ room.room_id }}</li>
                <li class="list-group-item">Name: {{ room.name }}</li>
                <li class="list-group-item">Joined members: {{ room.joined_members }}</li>
                <li class="list-group-item">Joined local members: {{ room.joined_local_members }}</li>
                <li class="list-group-item">Encryption: {% if room.encryption %} Yes {% else %} No {% endif %}</li>
                <li class="list-group-item">Federatable: {% if room.federatable %} Yes {% else %} No {% endif %}</li>
                <li class="list-group-item">Version: {{ room.version }}</li>
                <li class="list-group-item">Creator: {{ room.creator }}</li>
                <li class="list-group-item">Public: {% if room.public %} Yes {% else %} No {% endif %}</li>
                {% if room.local_members %}
                    <li class="list-group-item text-center">LOCAL MEMBERS</li>
                    {% for member in room.local_members %}
                        <li class="list-group-item"><a href="{% url 'users:detail' user_id=member %}"
                                                       class="link-dark">{{ member }}</a></li>
                    {% endfor %}
                {% endif %}
                {% if room.global_members %}
                    <li class="list-group-item text-center">GLOBAL MEMBERS</li>
                    {% for member in room.global_members %}
                        <li class="list-group-item"><a href="https://matrix.to/#/{{ member }}"
                                                       class="link-dark">{{ member }}</a></li>
                    {% endfor %}
                {% endif %}
            </ul>
        </div>
    </div>
{% endblock %}

templates/rooms/rooms.html
{% extends '_base.html' %}

{% block content %}
    <div class="py-2">
        <div class="d-flex justify-content-center">
            <nav>
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page=1"> << </a></li>
                        <li class="page-item"><a class="page-link"
                                                 href="?page={{ page_obj.previous_page_number }}"><</a></li>
                    {% endif %}
                    <li class="page-item"><a class="page-link" href="">{{ page_obj.number }}
                        of {{ page_obj.paginator.num_pages }}</a></li>
                    {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">></a>
                        </li>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
                            >> </a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
        <div class="table-responsive">
            <table class="table table-dark table-striped">
                <caption>Total rooms: {{ total_rooms }}</caption>
                <thead>
                <tr>
                    <th>ID</th>
                    <th>NAME</th>
                    <th>JOINED MEMBERS</th>
                    <th>ENCRYPTION</th>
                    <th>FEDERATABLE</th>
                </tr>
                </thead>
                <tbody>
                {% for room in rooms %}
                    <tr>
                        <th><a href="{% url 'rooms:detail' room_id=room.room_id %}" class="link-light">{{ room.room_id }}</a></th>
                        <td>{{ room.name|truncatechars:24 }}</td>
                        <td>{{ room.joined_members }}, {{ room.joined_local_members }} them is local</td>
                        <td>{% if room.encryption %} Yes {% else %} No {% endif %}</td>
                        <td>{% if room.federatable %} Yes {% else %} No {% endif %}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td>-</td>
                        <td>-</td>
                        <td>-</td>
                        <td>-</td>
                        <td>-</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}