dashboard/urls.py
from django.urls import path

from .views import DashboardView, InitView

app_name = 'dashboard'

urlpatterns = [
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('', InitView.as_view(), name='init'),
]

project/urls.py
from django.urls import path, include

urlpatterns = [
    path('users/', include('users.urls', namespace='users')),
    path('rooms/', include('rooms.urls', namespace='rooms')),
    path('server_notices/', include('server_notices.urls', namespace='server_notices')),
    path('', include('dashboard.urls', namespace='dashboard'))
]

rooms/urls.py
from django.urls import path

from .views import RoomsView, RoomView

app_name = 'rooms'

urlpatterns = [
    path('<str:room_id>/', RoomView.as_view(), name='detail'),
    path('', RoomsView.as_view(), name='list')
]

server_notices/urls.py
from django.urls import path

from .views import SendServerNoticeView

app_name = 'server_notices'

urlpatterns = [
    path('', SendServerNoticeView.as_view(), name='send')
]

templates/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>synapse_admin</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'main/background.css' %}">

    <link rel="icon" type="image/x-icon" href="{% static 'main/synapse_admin.png' %}">
</head>
<body class="bg-dark">
{% if not init_page_active %}
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <div class="container container-sm">
            <a class="navbar-brand" href="https://github.com/foresle/synapse_admin">synapse_admin</a>
            <button class="navbar-toggler" type="button" data-bs-target="#main_navbar" data-bs-toggle="collapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="main_navbar">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a href="{% url 'dashboard:dashboard' %}"
                           class="nav-link {% if dashboard_page_active %} active {% endif %} ">Dashboard</a>
                    </li>
                    <li class="nav-item"><a href="{% url 'users:list' %}"
                                            class="nav-link {% if users_page_active %} active {% endif %} ">Users</a>
                    </li>
                    <li class="nav-item"><a href="{% url 'rooms:list' %}"
                                            class="nav-link {% if rooms_page_active %} active {% endif %} ">Rooms</a>
                    </li>
                    <li class="nav-item"><a href="{% url 'server_notices:send' %}"
                                            class="nav-link {% if server_notices_page_active %} active {% endif %} ">Server
                        notices</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
{% endif %}

<div class="container container-sm" style="min-height: 85vh;">
    {% block content %}

    {% endblock %}
</div>

{% if not init_page_active %}
    <div class="container container-sm d-flex bg-dark justify-content-between flex-wrap py-2 my-2">
        <div class="text-muted"><a href="https://github.com/foresle/synapse_admin" class="link-light">synapse_admin</a>
            designed by
            <a href="https://github.com/foresle" class="link-light">foresle</a></div>
        <div class="text-muted">You can contribute to the project on the repository page.</div>
    </div>
{% endif %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

{% block optional_scripts %}

{% endblock %}
</body>
</html>