project/urls.py
from django.urls import path, include

urlpatterns = [
    path('users/', include('users.urls', namespace='users')),
    path('rooms/', include('rooms.urls', namespace='rooms')),
    path('server_notices/', include('server_notices.urls', namespace='server_notices')),
    path('', include('dashboard.urls', namespace='dashboard'))
]

rooms/urls.py
from django.urls import path

from .views import RoomsView, RoomView

app_name = 'rooms'

urlpatterns = [
    path('<str:room_id>/', RoomView.as_view(), name='detail'),
    path('', RoomsView.as_view(), name='list')
]

users/urls.py
from django.urls import path

from .views import UsersView, UserView, DeactivateUserView, ActivateUserView, SetAdminView, RevokeAdminView

app_name = 'users'

urlpatterns = [
    path('<str:user_id>/', UserView.as_view(), name='detail'),
    path('deactivate/<str:user_id>/', DeactivateUserView.as_view(), name='deactivate'),
    path('activate/<str:user_id>/', ActivateUserView.as_view(), name='activate'),
    path('set_admin/<str:user_id>/', SetAdminView.as_view(), name='set_admin'),
    path('revoke_admin/<str:user_id>/', RevokeAdminView.as_view(), name='revoke_admin'),
    path('', UsersView.as_view(), name='list')
]

users/forms.py
from django import forms
from django.conf import settings

from .helpers import deactivate_user, activate_user, set_admin, revoke_admin


class DeactivateUserForm(forms.Form):
    user_id = forms.CharField(label='User ID', initial='', required=True)

    def deactivate_user(self) -> bool:
        user_id = self.cleaned_data['user_id']

        return deactivate_user(
            access_token=settings.MATRIX_ADMIN_TOKEN,
            server_name=settings.MATRIX_DOMAIN,
            user_id=user_id
        )


class ActivateUserForm(forms.Form):
    user_id = forms.CharField(label='User ID', initial='', required=True)
    new_password = forms.CharField(label='New password', initial='', required=True, widget=forms.PasswordInput)

    def activate_user(self) -> bool:
        user_id = self.cleaned_data['user_id']
        new_password = self.cleaned_data['new_password']

        return activate_user(
            access_token=settings.MATRIX_ADMIN_TOKEN,
            server_name=settings.MATRIX_DOMAIN,
            user_id=user_id,
            new_password=new_password
        )


class SetAdminForm(forms.Form):
    user_id = forms.CharField(label='User ID', initial='', required=True)

    def set_admin(self) -> bool:
        user_id = self.cleaned_data['user_id']

        return set_admin(
            access_token=settings.MATRIX_ADMIN_TOKEN,
            server_name=settings.MATRIX_DOMAIN,
            user_id=user_id
        )


class RevokeAdminForm(forms.Form):
    user_id = forms.CharField(label='User ID', initial='', required=True)

    def revoke_admin(self) -> bool:
        user_id = self.cleaned_data['user_id']

        return revoke_admin(
            access_token=settings.MATRIX_ADMIN_TOKEN,
            server_name=settings.MATRIX_DOMAIN,
            user_id=user_id
        )

users/views.py
from django.core.cache import cache
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.views.generic import TemplateView, ListView, FormView
from django.conf import settings
from django.http import Http404
from django.contrib import messages

from .forms import DeactivateUserForm, ActivateUserForm, SetAdminForm, RevokeAdminForm


class UsersView(ListView):
    template_name = 'users/users.html'
    paginate_by = 10

    def get_queryset(self) -> tuple:
        return tuple(cache.get(settings.CACHED_USERS, {}).values())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        paginator = Paginator(self.object_list, self.paginate_by)
        page: str = self.request.GET.get('page')

        try:
            users = paginator.get_page(page)
        except PageNotAnInteger:
            users = paginator.get_page(1)
        except EmptyPage:
            users = paginator.get_page(paginator.num_pages)

        context['users'] = users
        context['cached_users_updated_at'] = cache.get(settings.CACHED_USERS_UPDATED_AT, None)
        context['total_users'] = paginator.count

        context['users_page_active'] = True

        return context


class UserView(TemplateView):
    template_name = 'users/user.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user_id = self.kwargs['user_id']
        user = cache.get(settings.CACHED_USERS, {}).get(user_id, None)
        if user is None:
            raise Http404('User not found.')

        cache.get(settings.CACHED_MEDIA_STATISTICS, {})

        context['user'] = user

        return context


class DeactivateUserView(FormView):
    template_name = 'users/deactivate.html'
    form_class = DeactivateUserForm

    def get_form(self, form_class=None):
        form: DeactivateUserForm = super().get_form(form_class=form_class)

        form.fields['user_id'].initial = self.kwargs['user_id']

        return form

    def form_valid(self, form):
        result: bool = form.deactivate_user()
        user_id: str = form.cleaned_data['user_id']

        messages.add_message(
            request=self.request,
            level=messages.SUCCESS if result else messages.ERROR,
            message=f'User {user_id} has been deactivated successfully!' if result else f'Deactivation unsuccessful.'
        )

        return super().form_valid(form=form)

    def get_success_url(self):
        return f'/users/deactivate/{self.kwargs["user_id"]}'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context


class ActivateUserView(FormView):
    template_name = 'users/activate.html'
    form_class = ActivateUserForm

    def get_form(self, form_class=None):
        form: DeactivateUserForm = super().get_form(form_class=form_class)

        form.fields['user_id'].initial = self.kwargs['user_id']

        return form

    def form_valid(self, form):
        result: bool = form.activate_user()
        user_id: str = form.cleaned_data['user_id']

        messages.add_message(
            request=self.request,
            level=messages.SUCCESS if result else messages.ERROR,
            message=f'User {user_id} has been activated successfully!' if result else f'Activation unsuccessful.'
        )

        return super().form_valid(form=form)

    def get_success_url(self):
        return f'/users/activate/{self.kwargs["user_id"]}'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context


class SetAdminView(FormView):
    template_name = 'users/set_admin.html'
    form_class = SetAdminForm

    def get_form(self, form_class=None):
        form: DeactivateUserForm = super().get_form(form_class=form_class)

        form.fields['user_id'].initial = self.kwargs['user_id']

        return form

    def form_valid(self, form):
        result: bool = form.set_admin()
        user_id: str = form.cleaned_data['user_id']

        messages.add_message(
            request=self.request,
            level=messages.SUCCESS if result else messages.ERROR,
            message=f'Admin access has been granted for {user_id} successfully!' if result else f'Granting admin '
                                                                                                f'rights failed.'
        )

        return super().form_valid(form=form)

    def get_success_url(self):
        return f'/users/set_admin/{self.kwargs["user_id"]}'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context


class RevokeAdminView(FormView):
    template_name = 'users/revoke_admin.html'
    form_class = RevokeAdminForm

    def get_form(self, form_class=None):
        form: DeactivateUserForm = super().get_form(form_class=form_class)

        form.fields['user_id'].initial = self.kwargs['user_id']

        return form

    def form_valid(self, form):
        result: bool = form.revoke_admin()
        user_id: str = form.cleaned_data['user_id']

        messages.add_message(
            request=self.request,
            level=messages.SUCCESS if result else messages.ERROR,
            message=f'Admin access has been revoked for {user_id} successfully!' if result else f'Revoking admin '
                                                                                                f'rights failed.'
        )

        return super().form_valid(form=form)

    def get_success_url(self):
        return f'/users/set_admin/{self.kwargs["user_id"]}'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context

templates/users/activate.html
{% extends '_base.html' %}

{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
    <div class="py-2 d-flex justify-content-center">
        <div class="card" style="width: 30rem;">
            <div class="card-body">
                <form action="" class="form" method="post">{% csrf_token %}
                    {% bootstrap_form form %}

                    {% bootstrap_button button_type="submit" button_class="btn-danger" content="Confirm account activation" %}
                </form>
            </div>
            {% if messages %}
                <div class="card-body">{% bootstrap_messages %}</div>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/users/deactivate.html
{% extends '_base.html' %}

{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
    <div class="py-2 d-flex justify-content-center">
        <div class="card" style="width: 30rem;">
            <div class="card-body">
                <form action="" class="form" method="post">{% csrf_token %}
                    {% bootstrap_form form %}

                    {% bootstrap_button button_type="submit" button_class="btn-danger" content="Confirm account deactivation" %}
                </form>
            </div>
            {% if messages %}
                <div class="card-body">{% bootstrap_messages %}</div>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/users/revoke_admin.html
{% extends '_base.html' %}

{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
    <div class="py-2 d-flex justify-content-center">
        <div class="card" style="width: 30rem;">
            <div class="card-body">
                <form action="" class="form" method="post">{% csrf_token %}
                    {% bootstrap_form form %}

                    {% bootstrap_button button_type="submit" button_class="btn-danger" content="Revoke admin" %}
                </form>
            </div>
            {% if messages %}
                <div class="card-body">{% bootstrap_messages %}</div>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/users/set_admin.html
{% extends '_base.html' %}

{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
    <div class="py-2 d-flex justify-content-center">
        <div class="card" style="width: 30rem;">
            <div class="card-body">
                <form action="" class="form" method="post">{% csrf_token %}
                    {% bootstrap_form form %}

                    {% bootstrap_button button_type="submit" button_class="btn-danger" content="Set admin" %}
                </form>
            </div>
            {% if messages %}
                <div class="card-body">{% bootstrap_messages %}</div>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/users/user.html
{% extends '_base.html' %}

{% block content %}
    <div class="my-2 p-2 d-flex flex-wrap justify-content-center">
        <div class="flex-shrink-0 m-2 d-flex flex-column">
            <img style="object-fit: cover"
                 src="{{ user.avatar_url|default:'https://cdn3.emoji.gg/emojis/9889-pain.gif' }}" alt="{{ user.name }}"
                 class="rounded text-light bg-light"
                 width="200px" height="200px">
            {% if not user.is_deactivated %}
                <a href="{% url 'users:deactivate' user_id=user.name %}" class="btn btn-danger mt-2">DEACTIVATE</a>
            {% else %}
                <a href="{% url 'users:activate' user_id=user.name %}" class="btn btn-success mt-2">ACTIVATE</a>
            {% endif %}
            {% if not user.is_admin %}
                <a href="{% url 'users:set_admin' user_id=user.name %}" class="btn btn-danger mt-2">MAKE ADMIN</a>
            {% else %}
                <a href="{% url 'users:revoke_admin' user_id=user.name %}" class="btn btn-success mt-2">REVOKE ADMIN</a>
            {% endif %}
        </div>
        <div class="flex-grow-1 m-2">
            <ul class="list-group">
                <li class="list-group-item text-center">PROFILE</li>
                <li class="list-group-item">Name: {{ user.name_without_server_name_ending }}</li>
                <li class="list-group-item">Display name: {{ user.display_name }}</li>
                <li class="list-group-item">Created at: {{ user.created_at }}</li>
                <li class="list-group-item">Last seen IP: {{ user.last_seen_ip }} - {{ user.last_seen_country }}</li>
                <li class="list-group-item">Last seen at: {{ user.last_seen_at }}</li>
                <li class="list-group-item">Last seen user agent: {{ user.last_seen_user_agent }}</li>
                <li class="list-group-item">Is admin: {% if user.is_admin %} Yes {% else %} No {% endif %}</li>
                <li class="list-group-item">Is deactivated: {% if user.is_deactivated %} Yes {% else %}
                    No {% endif %}</li>
                <li class="list-group-item text-center">MEDIA</li>
                <li class="list-group-item">Media count: {% if user.upload_media_count %}
                    {{ user.upload_media_count }} {% else %} 0 {% endif %} </li>
                <li class="list-group-item">Media size:  {% if user.size_of_upload_media %}
                    {{ user.size_of_upload_media }} {% else %} 0 {% endif %}</li>
            </ul>
        </div>
    </div>
{% endblock %}

templates/users/users.html
{% extends '_base.html' %}

{% block content %}
    <div class="py-2">
        <div class="d-flex justify-content-center">
            <nav>
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page=1"> << </a></li>
                        <li class="page-item"><a class="page-link"
                                                 href="?page={{ page_obj.previous_page_number }}"><</a></li>
                    {% endif %}
                    <li class="page-item"><a class="page-link" href="">{{ page_obj.number }}
                        of {{ page_obj.paginator.num_pages }}</a></li>
                    {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">></a>
                        </li>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
                            >> </a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
        <div class="table-responsive">
            <table class="table table-dark table-striped">
                <caption>Total users: {{ total_users }}</caption>
                <thead>
                <tr>
                    <th>NAME</th>
                    <th>DISPLAY NAME</th>
                    <th>CREATED AT</th>
                    <th>ADMIN</th>
                    <th>DEACTIVATED</th>
                    <th>L.S. IP</th>
                    <th>L.S. AT</th>
                    <th>L.S. COUNTRY</th>
                </tr>
                </thead>
                <tbody>
                {% for user in users %}
                    <tr>
                        <th><a href="{% url 'users:detail' user_id=user.name %}" class="link-light">{{ user.name_without_server_name_ending|truncatechars:20 }}</a></th>
                        <td>{{ user.display_name|truncatechars:24 }}</td>
                        <td>{{ user.created_at }}</td>
                        <td>{% if user.is_admin %} Yes {% else %} No {% endif %}</td>
                        <td>{% if user.is_deactivated %} Yes {% else %} No {% endif %}</td>
                        <td>{{ user.last_seen_ip }}</td>
                        <td>{{ user.last_seen_at }}</td>
                        <td>{{ user.last_seen_country }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td>-</td>
                        <td>-</td>
                        <td>-</td>
                        <td>-</td>
                        <td>-</td>
                        <td>-</td>
                        <td>-</td>
                        <td>-</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}